### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agarzon48** [4GeeksAcademy/Antoniomorales-Formulario#1]
Bien hecho, pero necesitamos algunas correcciones:

- Debes asegurarte de que todas las entradas se utilicen correctamente: fecha del tipo de entrada, correo electrónico, número de tipo de entrada, etc.
- También debes asegurarse de prevenir y validar el formulario de todas las formas en que HTML5 te permite (entradas, formatos, etc) y que complete los datos obligatorios.
- El archivo de entrada debe llamarse index, de lo contrario el servidor no lo encontrará
- Los labels de los iconos de las tarjetas no están bien configurados, por lo que no se selecciona la tarjeta correspondiente al hacer click en algunas de ellas
- Solo los campos radio tienen atributo name. Recuerda que el atributo name es el que nos permite registrar el campo, así que necesitas incluirlo en todos los inputs

**Comment by Antoniomorales17** [comment]
Gracias Adrián por el feedback, voy a revisarlo

**Comment by agarzon48** [comment]
Revisado de nuevo! Apruebo, porque has corregido los errores, pero ten en cuenta que te queda este:

```` HTML
<div class="bg-secondary rounded p-2">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1" />
                                    <label class="form-check-label text-white" for="inlineRadio1"><i class="fa-brands fa-cc-mastercard"></i></label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2" />
                                    <label class="form-check-label text-white" for="inlineRadio2"><i class="fa-brands fa-cc-visa"></i></label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option1" />
                                    <label class="form-check-label text-white" for="inlineRadio1"><i class="fa-brands fa-cc-diners-club"></i></label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="option2" />
                                    <label class="form-check-label text-white" for="inlineRadio2"><i class="fa-brands fa-cc-amex"></i></label>
                                </div>
                            </div>
````

Si te fijas, el atributo for de los labels se repite. Esto es lo que hace que solo se seleccionen dos tarjetas de las cuatro disponibles si haces click en sus iconos

**Comment by Antoniomorales17** [comment]
Ok Adrián, gracias y visto el error
